FROM rust:1.75-slim-buster AS builder

WORKDIR /build

COPY Cargo.toml . 
COPY Cargo.lock .
COPY ./src ./src

RUN cargo build --bin client

FROM debian:buster-slim
WORKDIR /client

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y tshark && \
    rm -rf /var/lib/apt/lists/*

ENV RUST_LOG=info

COPY --from=builder /build/target/debug/client .
COPY database.sql .

# ENTRYPOINT sleep 300h
ENTRYPOINT ./client
