version: "3.8"
services:
  scanner:
    image: https://ghcr.io/thearyadev/network_device_logger_scanner:latest 
    network_mode: host
    volumes:
      - ./data:/scanner/data
    environment:
      DATABASE_FILE_PATH: ./data/addrs.sqlite3
      DATABASE_SEED_FILE_PATH: ./database.sql
      PCAP_FILE_PATH: ./memfs/scan.pcap
      TSHARK_RUN_DURATION: 30
      TSHARK_TARGET_INTERFACE: enp0s31f6
      SLEEP: 30
  client:
    image: https://ghcr.io/thearyadev/network_device_logger_client:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/client/data
    environment:
      DATABASE_FILE_PATH: ./data/addrs.sqlite3
      DATABASE_SEED_FILE_PATH: ./database.sql

