name: Tests and CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docker-server-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the server image
        run: docker build . --tag ghcr.io/thearyadev/network_device_logger_scanner:latest --file ./Dockerfile.scanner
      - name: Save Docker image
        run: docker save ghcr.io/thearyadev/network_device_logger_scanner:latest | gzip > scanner_image.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: scanner-image
          path: scanner_image.tar.gz

  docker-client-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the frontend image
        run: docker build . --tag ghcr.io/thearyadev/network_device_logger_client:latest --file ./Dockerfile.client
      - name: Save Docker image
        run: docker save ghcr.io/thearyadev/network_device_logger_client:latest | gzip > client_image.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: client-image
          path: client_image.tar.gz

  publish:
    runs-on: ubuntu-latest
    needs:
      - docker-server-build
      - docker-client-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: scanner-image
          path: .
      - uses: actions/download-artifact@v3
        with:
          name: client-image
          path: .
      - name: Load Docker images
        run: |
          gunzip -c scanner_image.tar.gz | docker load
          gunzip -c client_image.tar.gz | docker load
      - name: Docker Login
        run: docker login --username thearyadev --password ${{ secrets.GH_PAT }} ghcr.io
      - name: Push images
        run: |
          docker push ghcr.io/thearyadev/network_device_logger_client:latest
          docker push ghcr.io/thearyadev/network_device_logger_scanner:latest
